// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR/SSG-safe (2026-07-25): prerender (Node) ortamında localStorage YOK →
// module-load'da ReferenceError, build çöker. typeof guard: istemcide localStorage
// (panel auth davranışı AYNEN korunur); prerender'da in-memory (auth zaten gerekmez).
const _ssrSafeStorage = typeof localStorage !== "undefined" ? localStorage : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: _ssrSafeStorage,
    persistSession: _ssrSafeStorage !== undefined,
    autoRefreshToken: true,
  }
});